# Generated by Django 3.1.2 on 2020-11-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='nombrebanco',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tipotarjeta',
            name='tipo_tarjeta',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
