# Generated by Django 3.1.2 on 2020-11-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20201112_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correoelectronico',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dpi',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
