# Generated by Django 3.1.2 on 2020-11-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_categoria_combustible_estado_fotografia_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='combustible',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='estado',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='combustible_vehiculo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='estado_vehiculo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Combustible',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
