# Generated by Django 3.1.2 on 2020-11-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20201113_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='puja',
            field=models.FloatField(null=True),
        ),
    ]
